stages:

  train-generate-with-gpt-4.1:
    cmd: >-
      python -m experiments.generate
      --input-df ./data/raw/neo4j-2024v1/train-00000-of-00001.parquet
      --output-df ./data/interim/neo4j-2024v1/gpt-4.1/train-trajectories.csv
      --workflow native_tool_call
      --provider azure
      --model gpt-4.1
      --verbose True
      --log-dir-path ./logs/
    deps:
      - data/raw/neo4j-2024v1/train-00000-of-00001.parquet
      - src/experiments/generate.py
    outs:
      - data/interim/neo4j-2024v1/gpt-4.1/train-trajectories.csv:
          persist: true

  test-generate-with-gpt-4.1:
    cmd: >-
      python -m experiments.generate
      --input-df ./data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      --output-df ./data/interim/neo4j-2024v1/gpt-4.1/test-trajectories.csv
      --workflow native_tool_call
      --provider azure
      --model gpt-4.1
      --verbose True
      --log-dir-path ./logs/
    deps:
      - data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      - src/experiments/generate.py
    outs:
      - data/interim/neo4j-2024v1/gpt-4.1/test-trajectories.csv:
          persist: true
  
  test-generate-with-neo4j-gemma-2-9b-it:
    cmd: >-
      python -m experiments.gen_neo4j_gemma_2_9b_it
      --input-df ./data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      --output-df ./data/interim/neo4j-2024v1/gemma-2-9b-it/test-cyphers.csv
    deps:
      - data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      - src/experiments/gen_neo4j_gemma_2_9b_it.py
    outs:
      - data/interim/neo4j-2024v1/gemma-2-9b-it/test-cyphers.csv:
          persist: true

  evaluate-train-gpt-4.1-generation:
    cmd: >-
      python -m experiments.evaluate
      --dataset-df ./data/raw/neo4j-2024v1/train-00000-of-00001.parquet
      --predictions-df ./data/interim/neo4j-2024v1/gpt-4.1/train-trajectories.csv
      --output-df ./data/interim/evaluations/gpt-4.1/train.csv
    deps:
      - data/raw/neo4j-2024v1/train-00000-of-00001.parquet
      - data/interim/neo4j-2024v1/gpt-4.1/train-trajectories.csv
      - src/experiments/evaluate.py
    outs:
      - data/interim/evaluations/gpt-4.1/train.csv:
          persist: true
  
  evaluate-test-gpt-4.1-generation:
    cmd: >-
      python -m experiments.evaluate
      --dataset-df ./data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      --predictions-df ./data/interim/neo4j-2024v1/gpt-4.1/test-trajectories.csv
      --output-df ./data/interim/evaluations/gpt-4.1/test.csv
    deps:
      - data/raw/neo4j-2024v1/test-00000-of-00001.parquet
      - data/interim/neo4j-2024v1/gpt-4.1/test-trajectories.csv
      - src/experiments/evaluate.py
    outs:
      - data/interim/evaluations/gpt-4.1/test.csv:
          persist: true