stages:
  preprocess_cypherbench_train_set:
    cmd: >-
      python text2cypher/preprocessing/cypherbench.py
      --input-path data/raw/text-to-cypher/CypherBench/train.json
      --schema-format-fn special_tokens
      --sample-format-fn special_tokens
      --output-path data/processed/text-to-cypher/CypherBench/train.csv
    deps:
      - data/raw/text-to-cypher/CypherBench/train.json
      - text2cypher/preprocessing/cypherbench.py
    outs:
      - data/processed/text-to-cypher/CypherBench/train.csv
    
  preprocess_cypherbench_test_set:
    cmd: >-
      python text2cypher/preprocessing/cypherbench.py
      --input-path data/raw/text-to-cypher/CypherBench/test.json
      --schema-format-fn special_tokens
      --sample-format-fn special_tokens
      --output-path data/processed/text-to-cypher/CypherBench/test.csv
    deps:
      - data/raw/text-to-cypher/CypherBench/test.json
      - text2cypher/preprocessing/cypherbench.py
    outs:
      - data/processed/text-to-cypher/CypherBench/test.csv
  
  train_t5_small_cypherbench:
    cmd: >-
      python text2cypher/modeling/train.py
      --model-name google/flan-t5-small
      --train-data data/processed/text-to-cypher/CypherBench/train.csv
      --hyperparameters parameters/any.yaml
      --output-dir models/t5-small-cypherbench
    deps:
      - text2cypher/modeling/train.py
      - data/processed/text-to-cypher/CypherBench/train.csv
      - parameters/any.yaml
    outs:
      - models/t5-small-cypherbench